using Ploeh.AutoFixture.NUnit2;

namespace Raging.Toolbox.Testing.FakeItEasy
{
    /// <summary>
    ///     Provides auto-generated data specimens generated by AutoFixture and FakeItEasy,
    ///     as an extention to NUnit TestCase attribute.
    /// </summary>
    public class AutoFakeDataAttribute : AutoDataAttribute
    {
        public AutoFakeDataAttribute()
            : base(Auto.Fixture) { }
    }
}